name: Build pushed changes

on:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
#    - uses: fwal/setup-swift@v1
#      with:
#        swift-version: "5.5"
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
