name: Build pushed changes

on:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme Locus -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12' build

    - name: Run tests
      run: xcodebuild -scheme Locus -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12' test

